spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:postgresql://localhost:5433/analytics_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: analytics_service.event.LinkClickedEvent
        spring.json.use.type.headers: false

server:
  port: 8081

logging:
  level:
    org.springframework.kafka: INFO
    org.hibernate.SQL: INFO